[database]
host = "172.16.100.4"
port = 5432
user = "webapp_user"
password = "securepassword"  # Убедитесь, что пароль совпадает с установленным в PostgreSQL
dbname = "webapp_db"

[server]
port = 5000
